<!Doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>xKnight</title>
    <link rel="icon" type="image/x-icon" href="assets/pictures/favicon/knightFavicon.png">

    <script defer src="View/startView.js"></script>
    <link rel="stylesheet" href="View/default.css"/>
</head>
<body>

<h1>
    <marquee scrolldelay="200" scrollamount="50">xKnight</marquee>
</h1>

<button class="shadowBtn" onclick="typeWriter()">Das Erwachen der Story</button>

<main id="startContainer">
    <div id="storyTextFieldFrontPage">
        <textarea class="storyTextArea" id="storyTextfield" readonly rows="32" cols="66"></textarea>
    </div>
    <br>
    <br>
    <div id="knightNumberField">
        <form action="" method="POST">
            <input type="hidden" id="mode" name="mode" value="<?= $myMode ?>">
            <div class="knightNumberBtns">
                <button onclick="divideBy2()" type="button" class="shadowBtn" id="DivideBtn">weniger Ritter</button>
                <input readonly name="knightNumber" id="knightNumber" maxlength="5" value="2">
                <button onclick="multiplyBy2()" type="button" class="shadowBtn" id="multiplyBtn">mehr Ritter
                </button>
            </div>
            <br>
            <br>
            <button type="submit" id="submitButtonStart" class="shadowBtn">beginne die Spiele</button>
        </form>
    </div>
</main>

</body>
</html>