<!Doctype html>
<html>
<head>
    <link rel="stylesheet" href="View/default.css"/>

    <script defer src="View/sound.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

<div class="wholeWinningScreen">
<div class="winnerField">
    And The Xnight of the Universe is <?php
    echo $knight->getName(); ?> with <?php
    echo $knight->getLifepoints(); ?> lifepoints.

    <br>
    <br>
    <br>


    <form action="" method="POST">
        <input type="hidden" id="mode" name="mode" value="<?php echo $myMode ?>">
        <button type="submit" id="submitButtonReset" class="shadowBtn">Auf eine neue Runde</button>
    </form>
</div>
</div>



</body>
</html>