<!Doctype html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="assets/pictures/favicon/knightFavicon.png">

    <link rel="stylesheet" href="View/default.css"/>
    <script defer src="View/sound.js"></script>
</head>

<body>

<div class="winnerField">
    And The Xnight of the Universe is
    <?= $knight->getName(); ?> with
    <?= $knight->getLifepoints(); ?> lifepoints.
    <br>
    <br>
    <br>
    <form action="" method="POST">
        <input type="hidden" id="mode" name="mode" value="<?= $myMode ?>">
        <button type="submit" class="shadowBtn">Auf eine neue Runde</button>
    </form>
</div>

</body>
</html>